# Generated by Django 3.2.6 on 2026-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20260203_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='http_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
